version: '3'
services:
  ## Server
  server:
    image: huikaihoo/test-calc-server:1.0
    build: ./server
    expose:
      - 8080
    environment:
      NODE_ENV: development
    ports:
      - 8080:8080
  ## Client
  client:
    image: huikaihoo/test-calc-client:1.0
    build: ./client
    links:
      - server
    expose:
      - 3000
    ports:
      - 3000:3000
